### ISSUE TITLE
Perl::Critic being instantiated for each file is very slow

### ISSUE THREAD

**Issue by holcapek** [Perl-Critic/Test-Perl-Critic#10]
Not sure if this is intended or not, but [instantiating Perl::Critic for each file to be criticized](https://metacpan.org/source/THALJEF/Test-Perl-Critic-1.03/lib/Test/Perl/Critic.pm#L64) makes `critic_ok` pretty slow.

Running `perlcritic` upon set of files is roughly 4 times faster than `Test::Perl::Critic`.

Would it be possible to initialize `Perl::Critic` just once for all files?

Thanks!

**Comment by holcapek** [comment]
Would something trivial like https://github.com/Perl-Critic/Test-Perl-Critic/pull/11 work? I am not sure of consequences to `all_critic_ok` as it's using `MCE`.
In case you like the meaning but don't like the look, I can make it look more appealing, of course :-)

**Comment by petdance** [comment]
Done.  It's in the just-pushed-to-CPAN 1.04.  Thanks for the nudge.
