### ISSUE TITLE
Fresh install fails to install PPI because of missing File::Remove dependency

### ISSUE THREAD

**Issue by daoswald** [Perl-Critic/Test-Perl-Critic#4]
A fresh install on a reasonably pristine Perl 5.22 system will fail because PPI requires File::Remove, but probably doesn't name it within its dependencies.  While this is more a PPI issue, it does break Test::Perl::Critic, so I'm mentioning it here.

**Comment by dolmen** [comment]
But File::Remove is declared in PPI's dependencies: https://metacpan.org/source/MITHALDU/PPI-1.220/META.yml#L8

What CPAN client did you use to install Test::Perl::Critic?

**Comment by giovanism** [comment]
Shouldn't this issue be closed already? Unless @daoswald gives more details.
