### ISSUE TITLE
should require newer version of MCE

### ISSUE THREAD

**Issue by chorny** [Perl-Critic/Test-Perl-Critic#6]
Version 1.827 has fixes for running under taint mode. As the error appears in the END block, it may lead to errors even if tests if skipped after loading Test::Perl::Critic. See for ex. http://www.cpantesters.org/cpan/report/606aa06d-6c1b-1014-b32f-3adcd52a00bf

**Comment by petdance** [comment]
Updated the requirement in 2a03f14.  Thanks.
