### ISSUE TITLE
Issues link in POD is wrong

### ISSUE THREAD

**Issue by dr-kd** [Perl-Critic/Test-Perl-Critic#7]
it points to RT, should point to https://github.com/Perl-Critic/Test-Perl-Critic/issues

**Comment by petdance** [comment]
Which version are you running?  Which file specifically are you looking in?

**Comment by dr-kd** [comment]
as per here https://metacpan.org/pod/Test::Perl::Critic#BUGS

**Comment by petdance** [comment]
Fixed in 827c8e6.  Thank you.
